export const ActionType = {
  //CONTROLLER
  AUTHENTICATION_HANDLER : 'AUTHENTICATION_HANDLER',
  MESSAGE_HANDLER : 'MESSAGE_HANDLER',

  //USERS
  FETCH_USERS_REQUEST : 'FETCH_USERS_REQUEST',
  FETCH_USERS_SUCCESS : 'FETCH_USERS_SUCCESS',
  FETCH_USERS_ERROR : 'FETCH_USERS_ERROR',

  FETCH_USERS_BY_ID_REQUEST: 'FETCH_USERS_BY_ID_REQUEST',
  FETCH_USERS_BY_ID_SUCCESS: 'FETCH_USERS_BY_ID_SUCCESS',
  FETCH_USERS_BY_ID_ERROR: 'FETCH_USERS_BY_ID_ERROR',
};